// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Protocol.proto</summary>
public static partial class ProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for Protocol.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5Qcm90b2NvbC5wcm90byJBCglPZmljaXVEVE8SEAoIaWRPZmljaXUYASAB",
          "KAkSEAoIdXNlcm5hbWUYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkiLQoFQ3Vy",
          "c2ESEgoKbnJQZXJzb2FuZRgBIAEoBRIQCghjYXBNb3RvchgCIAEoBSJBCghD",
          "dXJzYURUTxIPCgdpZEN1cnNhGAEgASgJEhIKCm5yUGVyc29hbmUYAiABKAUS",
          "EAoIY2FwTW90b3IYAyABKAUiPQoLUGFydGljaXBhbnQSDAoEbnVtZRgBIAEo",
          "CRIOCgZlY2hpcGEYAiABKAkSEAoIY2FwTW90b3IYAyABKAUiVwoOUGFydGlj",
          "aXBhbnREVE8SFQoNaWRQYXJ0aWNpcGFudBgBIAEoCRIMCgRudW1lGAIgASgJ",
          "Eg4KBmVjaGlwYRgDIAEoCRIQCghjYXBNb3RvchgEIAEoBSI6ChBQYXJ0aWNp",
          "cGFudEN1cnNhEhUKDWlkUGFydGljaXBhbnQYASABKAkSDwoHaWRDdXJzYRgC",
          "IAEoCSLcAwoHUmVxdWVzdBIbCgR0eXBlGAEgASgOMg0uUmVxdWVzdC5UeXBl",
          "Eh0KCW9maWNpdURUTxgCIAEoCzIKLk9maWNpdURUTxIQCgh1c2VybmFtZRgD",
          "IAEoCRIQCghwYXNzd29yZBgEIAEoCRIMCgRudW1lGAYgASgJEg4KBmVjaGlw",
          "YRgHIAEoCRIQCghjYXBNb3RvchgIIAEoBRIPCgdpZEN1cnNhGAkgASgJEisK",
          "EHBhcnRpY2lwYW50Q3Vyc2EYCiABKAsyES5QYXJ0aWNpcGFudEN1cnNhEhsK",
          "CGN1cnNhRFRPGAsgASgLMgkuQ3Vyc2FEVE8i5QEKBFR5cGUSCwoHVW5rbm93",
          "bhAAEgkKBUxvZ2luEAESFwoTR2V0T2ZpY2l1QnlVc2VyUGFzcxACEgoKBkxv",
          "Z291dBADEhYKEkdldEFsbFBhcnRpY2lwYW50cxAEEg8KC0dldEFsbEN1cnNh",
          "EAUSHAoYR2V0QWxsUGFydGljaXBhbnRzQnlUZWFtEAYSDQoJR2V0RWNoaXBl",
          "EAcSEgoOR2V0UGFydGljaXBhbnQQCBIMCghHZXRDdXJzYRAJEhcKE0FkZFBh",
          "cnRpY2lwYW50Q3Vyc2EQChIPCgtVcGRhdGVDdXJzYRALIqIDCghSZXNwb25z",
          "ZRIcCgR0eXBlGAEgASgOMg4uUmVzcG9uc2UuVHlwZRIOCgZlcm9hcmUYAiAB",
          "KAkSHQoJb2ZpY2l1RFRPGAMgASgLMgouT2ZpY2l1RFRPEhsKCGN1cnNlRFRP",
          "GAQgAygLMgkuQ3Vyc2FEVE8SIgoMcGFydGljaXBhbnRpGAUgAygLMgwuUGFy",
          "dGljaXBhbnQSDgoGZWNoaXBlGAYgASgJEicKDnBhcnRpY2lwYW50RFRPGAcg",
          "ASgLMg8uUGFydGljaXBhbnREVE8SFQoFY3Vyc2EYCCABKAsyBi5DdXJzYSK3",
          "AQoEVHlwZRILCgdVbmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEhcKE0dl",
          "dE9maWNpdUJ5VXNlclBhc3MQAxIPCgtHZXRBbGxDdXJzYRAEEhYKEkdldEFs",
          "bFBhcnRpY2lwYW50cxAFEg0KCUdldEVjaGlwZRAGEhIKDkdldFBhcnRpY2lw",
          "YW50EAcSDAoIR2V0Q3Vyc2EQCBIcChhOZXdQYXJ0aWNpcGFudEN1cnNhQWRk",
          "ZWQQCWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::OficiuDTO), global::OficiuDTO.Parser, new[]{ "IdOficiu", "Username", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Cursa), global::Cursa.Parser, new[]{ "NrPersoane", "CapMotor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CursaDTO), global::CursaDTO.Parser, new[]{ "IdCursa", "NrPersoane", "CapMotor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Participant), global::Participant.Parser, new[]{ "Nume", "Echipa", "CapMotor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ParticipantDTO), global::ParticipantDTO.Parser, new[]{ "IdParticipant", "Nume", "Echipa", "CapMotor" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ParticipantCursa), global::ParticipantCursa.Parser, new[]{ "IdParticipant", "IdCursa" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Type", "OficiuDTO", "Username", "Password", "Nume", "Echipa", "CapMotor", "IdCursa", "ParticipantCursa", "CursaDTO" }, null, new[]{ typeof(global::Request.Types.Type) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Type", "Eroare", "OficiuDTO", "CurseDTO", "Participanti", "Echipe", "ParticipantDTO", "Cursa" }, null, new[]{ typeof(global::Response.Types.Type) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class OficiuDTO : pb::IMessage<OficiuDTO> {
  private static readonly pb::MessageParser<OficiuDTO> _parser = new pb::MessageParser<OficiuDTO>(() => new OficiuDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<OficiuDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OficiuDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OficiuDTO(OficiuDTO other) : this() {
    idOficiu_ = other.idOficiu_;
    username_ = other.username_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public OficiuDTO Clone() {
    return new OficiuDTO(this);
  }

  /// <summary>Field number for the "idOficiu" field.</summary>
  public const int IdOficiuFieldNumber = 1;
  private string idOficiu_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdOficiu {
    get { return idOficiu_; }
    set {
      idOficiu_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 3;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as OficiuDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(OficiuDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IdOficiu != other.IdOficiu) return false;
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IdOficiu.Length != 0) hash ^= IdOficiu.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IdOficiu.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(IdOficiu);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IdOficiu.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdOficiu);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(OficiuDTO other) {
    if (other == null) {
      return;
    }
    if (other.IdOficiu.Length != 0) {
      IdOficiu = other.IdOficiu;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          IdOficiu = input.ReadString();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Cursa : pb::IMessage<Cursa> {
  private static readonly pb::MessageParser<Cursa> _parser = new pb::MessageParser<Cursa>(() => new Cursa());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Cursa> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Cursa() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Cursa(Cursa other) : this() {
    nrPersoane_ = other.nrPersoane_;
    capMotor_ = other.capMotor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Cursa Clone() {
    return new Cursa(this);
  }

  /// <summary>Field number for the "nrPersoane" field.</summary>
  public const int NrPersoaneFieldNumber = 1;
  private int nrPersoane_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int NrPersoane {
    get { return nrPersoane_; }
    set {
      nrPersoane_ = value;
    }
  }

  /// <summary>Field number for the "capMotor" field.</summary>
  public const int CapMotorFieldNumber = 2;
  private int capMotor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CapMotor {
    get { return capMotor_; }
    set {
      capMotor_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Cursa);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Cursa other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (NrPersoane != other.NrPersoane) return false;
    if (CapMotor != other.CapMotor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (NrPersoane != 0) hash ^= NrPersoane.GetHashCode();
    if (CapMotor != 0) hash ^= CapMotor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (NrPersoane != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(NrPersoane);
    }
    if (CapMotor != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(CapMotor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (NrPersoane != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrPersoane);
    }
    if (CapMotor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CapMotor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Cursa other) {
    if (other == null) {
      return;
    }
    if (other.NrPersoane != 0) {
      NrPersoane = other.NrPersoane;
    }
    if (other.CapMotor != 0) {
      CapMotor = other.CapMotor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          NrPersoane = input.ReadInt32();
          break;
        }
        case 16: {
          CapMotor = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class CursaDTO : pb::IMessage<CursaDTO> {
  private static readonly pb::MessageParser<CursaDTO> _parser = new pb::MessageParser<CursaDTO>(() => new CursaDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<CursaDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CursaDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CursaDTO(CursaDTO other) : this() {
    idCursa_ = other.idCursa_;
    nrPersoane_ = other.nrPersoane_;
    capMotor_ = other.capMotor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public CursaDTO Clone() {
    return new CursaDTO(this);
  }

  /// <summary>Field number for the "idCursa" field.</summary>
  public const int IdCursaFieldNumber = 1;
  private string idCursa_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdCursa {
    get { return idCursa_; }
    set {
      idCursa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nrPersoane" field.</summary>
  public const int NrPersoaneFieldNumber = 2;
  private int nrPersoane_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int NrPersoane {
    get { return nrPersoane_; }
    set {
      nrPersoane_ = value;
    }
  }

  /// <summary>Field number for the "capMotor" field.</summary>
  public const int CapMotorFieldNumber = 3;
  private int capMotor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CapMotor {
    get { return capMotor_; }
    set {
      capMotor_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as CursaDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(CursaDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IdCursa != other.IdCursa) return false;
    if (NrPersoane != other.NrPersoane) return false;
    if (CapMotor != other.CapMotor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IdCursa.Length != 0) hash ^= IdCursa.GetHashCode();
    if (NrPersoane != 0) hash ^= NrPersoane.GetHashCode();
    if (CapMotor != 0) hash ^= CapMotor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IdCursa.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(IdCursa);
    }
    if (NrPersoane != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(NrPersoane);
    }
    if (CapMotor != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CapMotor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IdCursa.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCursa);
    }
    if (NrPersoane != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrPersoane);
    }
    if (CapMotor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CapMotor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(CursaDTO other) {
    if (other == null) {
      return;
    }
    if (other.IdCursa.Length != 0) {
      IdCursa = other.IdCursa;
    }
    if (other.NrPersoane != 0) {
      NrPersoane = other.NrPersoane;
    }
    if (other.CapMotor != 0) {
      CapMotor = other.CapMotor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          IdCursa = input.ReadString();
          break;
        }
        case 16: {
          NrPersoane = input.ReadInt32();
          break;
        }
        case 24: {
          CapMotor = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class Participant : pb::IMessage<Participant> {
  private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Participant> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Participant() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Participant(Participant other) : this() {
    nume_ = other.nume_;
    echipa_ = other.echipa_;
    capMotor_ = other.capMotor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Participant Clone() {
    return new Participant(this);
  }

  /// <summary>Field number for the "nume" field.</summary>
  public const int NumeFieldNumber = 1;
  private string nume_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Nume {
    get { return nume_; }
    set {
      nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "echipa" field.</summary>
  public const int EchipaFieldNumber = 2;
  private string echipa_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Echipa {
    get { return echipa_; }
    set {
      echipa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "capMotor" field.</summary>
  public const int CapMotorFieldNumber = 3;
  private int capMotor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CapMotor {
    get { return capMotor_; }
    set {
      capMotor_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Participant);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Participant other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Nume != other.Nume) return false;
    if (Echipa != other.Echipa) return false;
    if (CapMotor != other.CapMotor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Nume.Length != 0) hash ^= Nume.GetHashCode();
    if (Echipa.Length != 0) hash ^= Echipa.GetHashCode();
    if (CapMotor != 0) hash ^= CapMotor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Nume.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Nume);
    }
    if (Echipa.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Echipa);
    }
    if (CapMotor != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CapMotor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Nume.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
    }
    if (Echipa.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Echipa);
    }
    if (CapMotor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CapMotor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Participant other) {
    if (other == null) {
      return;
    }
    if (other.Nume.Length != 0) {
      Nume = other.Nume;
    }
    if (other.Echipa.Length != 0) {
      Echipa = other.Echipa;
    }
    if (other.CapMotor != 0) {
      CapMotor = other.CapMotor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Nume = input.ReadString();
          break;
        }
        case 18: {
          Echipa = input.ReadString();
          break;
        }
        case 24: {
          CapMotor = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class ParticipantDTO : pb::IMessage<ParticipantDTO> {
  private static readonly pb::MessageParser<ParticipantDTO> _parser = new pb::MessageParser<ParticipantDTO>(() => new ParticipantDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ParticipantDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ParticipantDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ParticipantDTO(ParticipantDTO other) : this() {
    idParticipant_ = other.idParticipant_;
    nume_ = other.nume_;
    echipa_ = other.echipa_;
    capMotor_ = other.capMotor_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ParticipantDTO Clone() {
    return new ParticipantDTO(this);
  }

  /// <summary>Field number for the "idParticipant" field.</summary>
  public const int IdParticipantFieldNumber = 1;
  private string idParticipant_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdParticipant {
    get { return idParticipant_; }
    set {
      idParticipant_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nume" field.</summary>
  public const int NumeFieldNumber = 2;
  private string nume_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Nume {
    get { return nume_; }
    set {
      nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "echipa" field.</summary>
  public const int EchipaFieldNumber = 3;
  private string echipa_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Echipa {
    get { return echipa_; }
    set {
      echipa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "capMotor" field.</summary>
  public const int CapMotorFieldNumber = 4;
  private int capMotor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CapMotor {
    get { return capMotor_; }
    set {
      capMotor_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ParticipantDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ParticipantDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IdParticipant != other.IdParticipant) return false;
    if (Nume != other.Nume) return false;
    if (Echipa != other.Echipa) return false;
    if (CapMotor != other.CapMotor) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IdParticipant.Length != 0) hash ^= IdParticipant.GetHashCode();
    if (Nume.Length != 0) hash ^= Nume.GetHashCode();
    if (Echipa.Length != 0) hash ^= Echipa.GetHashCode();
    if (CapMotor != 0) hash ^= CapMotor.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IdParticipant.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(IdParticipant);
    }
    if (Nume.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Nume);
    }
    if (Echipa.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Echipa);
    }
    if (CapMotor != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CapMotor);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IdParticipant.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdParticipant);
    }
    if (Nume.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
    }
    if (Echipa.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Echipa);
    }
    if (CapMotor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CapMotor);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ParticipantDTO other) {
    if (other == null) {
      return;
    }
    if (other.IdParticipant.Length != 0) {
      IdParticipant = other.IdParticipant;
    }
    if (other.Nume.Length != 0) {
      Nume = other.Nume;
    }
    if (other.Echipa.Length != 0) {
      Echipa = other.Echipa;
    }
    if (other.CapMotor != 0) {
      CapMotor = other.CapMotor;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          IdParticipant = input.ReadString();
          break;
        }
        case 18: {
          Nume = input.ReadString();
          break;
        }
        case 26: {
          Echipa = input.ReadString();
          break;
        }
        case 32: {
          CapMotor = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class ParticipantCursa : pb::IMessage<ParticipantCursa> {
  private static readonly pb::MessageParser<ParticipantCursa> _parser = new pb::MessageParser<ParticipantCursa>(() => new ParticipantCursa());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ParticipantCursa> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ParticipantCursa() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ParticipantCursa(ParticipantCursa other) : this() {
    idParticipant_ = other.idParticipant_;
    idCursa_ = other.idCursa_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ParticipantCursa Clone() {
    return new ParticipantCursa(this);
  }

  /// <summary>Field number for the "idParticipant" field.</summary>
  public const int IdParticipantFieldNumber = 1;
  private string idParticipant_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdParticipant {
    get { return idParticipant_; }
    set {
      idParticipant_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "idCursa" field.</summary>
  public const int IdCursaFieldNumber = 2;
  private string idCursa_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdCursa {
    get { return idCursa_; }
    set {
      idCursa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ParticipantCursa);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ParticipantCursa other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IdParticipant != other.IdParticipant) return false;
    if (IdCursa != other.IdCursa) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IdParticipant.Length != 0) hash ^= IdParticipant.GetHashCode();
    if (IdCursa.Length != 0) hash ^= IdCursa.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IdParticipant.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(IdParticipant);
    }
    if (IdCursa.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IdCursa);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IdParticipant.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdParticipant);
    }
    if (IdCursa.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCursa);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ParticipantCursa other) {
    if (other == null) {
      return;
    }
    if (other.IdParticipant.Length != 0) {
      IdParticipant = other.IdParticipant;
    }
    if (other.IdCursa.Length != 0) {
      IdCursa = other.IdCursa;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          IdParticipant = input.ReadString();
          break;
        }
        case 18: {
          IdCursa = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Request : pb::IMessage<Request> {
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request(Request other) : this() {
    type_ = other.type_;
    oficiuDTO_ = other.oficiuDTO_ != null ? other.oficiuDTO_.Clone() : null;
    username_ = other.username_;
    password_ = other.password_;
    nume_ = other.nume_;
    echipa_ = other.echipa_;
    capMotor_ = other.capMotor_;
    idCursa_ = other.idCursa_;
    participantCursa_ = other.participantCursa_ != null ? other.participantCursa_.Clone() : null;
    cursaDTO_ = other.cursaDTO_ != null ? other.cursaDTO_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::Request.Types.Type type_ = global::Request.Types.Type.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Request.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "oficiuDTO" field.</summary>
  public const int OficiuDTOFieldNumber = 2;
  private global::OficiuDTO oficiuDTO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::OficiuDTO OficiuDTO {
    get { return oficiuDTO_; }
    set {
      oficiuDTO_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 3;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 4;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nume" field.</summary>
  public const int NumeFieldNumber = 6;
  private string nume_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Nume {
    get { return nume_; }
    set {
      nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "echipa" field.</summary>
  public const int EchipaFieldNumber = 7;
  private string echipa_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Echipa {
    get { return echipa_; }
    set {
      echipa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "capMotor" field.</summary>
  public const int CapMotorFieldNumber = 8;
  private int capMotor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CapMotor {
    get { return capMotor_; }
    set {
      capMotor_ = value;
    }
  }

  /// <summary>Field number for the "idCursa" field.</summary>
  public const int IdCursaFieldNumber = 9;
  private string idCursa_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string IdCursa {
    get { return idCursa_; }
    set {
      idCursa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "participantCursa" field.</summary>
  public const int ParticipantCursaFieldNumber = 10;
  private global::ParticipantCursa participantCursa_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ParticipantCursa ParticipantCursa {
    get { return participantCursa_; }
    set {
      participantCursa_ = value;
    }
  }

  /// <summary>Field number for the "cursaDTO" field.</summary>
  public const int CursaDTOFieldNumber = 11;
  private global::CursaDTO cursaDTO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::CursaDTO CursaDTO {
    get { return cursaDTO_; }
    set {
      cursaDTO_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(OficiuDTO, other.OficiuDTO)) return false;
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    if (Nume != other.Nume) return false;
    if (Echipa != other.Echipa) return false;
    if (CapMotor != other.CapMotor) return false;
    if (IdCursa != other.IdCursa) return false;
    if (!object.Equals(ParticipantCursa, other.ParticipantCursa)) return false;
    if (!object.Equals(CursaDTO, other.CursaDTO)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::Request.Types.Type.Unknown) hash ^= Type.GetHashCode();
    if (oficiuDTO_ != null) hash ^= OficiuDTO.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (Nume.Length != 0) hash ^= Nume.GetHashCode();
    if (Echipa.Length != 0) hash ^= Echipa.GetHashCode();
    if (CapMotor != 0) hash ^= CapMotor.GetHashCode();
    if (IdCursa.Length != 0) hash ^= IdCursa.GetHashCode();
    if (participantCursa_ != null) hash ^= ParticipantCursa.GetHashCode();
    if (cursaDTO_ != null) hash ^= CursaDTO.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Type != global::Request.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (oficiuDTO_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(OficiuDTO);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Password);
    }
    if (Nume.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Nume);
    }
    if (Echipa.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Echipa);
    }
    if (CapMotor != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(CapMotor);
    }
    if (IdCursa.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(IdCursa);
    }
    if (participantCursa_ != null) {
      output.WriteRawTag(82);
      output.WriteMessage(ParticipantCursa);
    }
    if (cursaDTO_ != null) {
      output.WriteRawTag(90);
      output.WriteMessage(CursaDTO);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::Request.Types.Type.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (oficiuDTO_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(OficiuDTO);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (Nume.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
    }
    if (Echipa.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Echipa);
    }
    if (CapMotor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CapMotor);
    }
    if (IdCursa.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCursa);
    }
    if (participantCursa_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantCursa);
    }
    if (cursaDTO_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CursaDTO);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::Request.Types.Type.Unknown) {
      Type = other.Type;
    }
    if (other.oficiuDTO_ != null) {
      if (oficiuDTO_ == null) {
        OficiuDTO = new global::OficiuDTO();
      }
      OficiuDTO.MergeFrom(other.OficiuDTO);
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    if (other.Nume.Length != 0) {
      Nume = other.Nume;
    }
    if (other.Echipa.Length != 0) {
      Echipa = other.Echipa;
    }
    if (other.CapMotor != 0) {
      CapMotor = other.CapMotor;
    }
    if (other.IdCursa.Length != 0) {
      IdCursa = other.IdCursa;
    }
    if (other.participantCursa_ != null) {
      if (participantCursa_ == null) {
        ParticipantCursa = new global::ParticipantCursa();
      }
      ParticipantCursa.MergeFrom(other.ParticipantCursa);
    }
    if (other.cursaDTO_ != null) {
      if (cursaDTO_ == null) {
        CursaDTO = new global::CursaDTO();
      }
      CursaDTO.MergeFrom(other.CursaDTO);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Request.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          if (oficiuDTO_ == null) {
            OficiuDTO = new global::OficiuDTO();
          }
          input.ReadMessage(OficiuDTO);
          break;
        }
        case 26: {
          Username = input.ReadString();
          break;
        }
        case 34: {
          Password = input.ReadString();
          break;
        }
        case 50: {
          Nume = input.ReadString();
          break;
        }
        case 58: {
          Echipa = input.ReadString();
          break;
        }
        case 64: {
          CapMotor = input.ReadInt32();
          break;
        }
        case 74: {
          IdCursa = input.ReadString();
          break;
        }
        case 82: {
          if (participantCursa_ == null) {
            ParticipantCursa = new global::ParticipantCursa();
          }
          input.ReadMessage(ParticipantCursa);
          break;
        }
        case 90: {
          if (cursaDTO_ == null) {
            CursaDTO = new global::CursaDTO();
          }
          input.ReadMessage(CursaDTO);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Request message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Login")] Login = 1,
      [pbr::OriginalName("GetOficiuByUserPass")] GetOficiuByUserPass = 2,
      [pbr::OriginalName("Logout")] Logout = 3,
      [pbr::OriginalName("GetAllParticipants")] GetAllParticipants = 4,
      [pbr::OriginalName("GetAllCursa")] GetAllCursa = 5,
      [pbr::OriginalName("GetAllParticipantsByTeam")] GetAllParticipantsByTeam = 6,
      [pbr::OriginalName("GetEchipe")] GetEchipe = 7,
      [pbr::OriginalName("GetParticipant")] GetParticipant = 8,
      [pbr::OriginalName("GetCursa")] GetCursa = 9,
      [pbr::OriginalName("AddParticipantCursa")] AddParticipantCursa = 10,
      [pbr::OriginalName("UpdateCursa")] UpdateCursa = 11,
    }

  }
  #endregion

}

public sealed partial class Response : pb::IMessage<Response> {
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtocolReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response(Response other) : this() {
    type_ = other.type_;
    eroare_ = other.eroare_;
    oficiuDTO_ = other.oficiuDTO_ != null ? other.oficiuDTO_.Clone() : null;
    curseDTO_ = other.curseDTO_.Clone();
    participanti_ = other.participanti_.Clone();
    echipe_ = other.echipe_;
    participantDTO_ = other.participantDTO_ != null ? other.participantDTO_.Clone() : null;
    cursa_ = other.cursa_ != null ? other.cursa_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::Response.Types.Type type_ = global::Response.Types.Type.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Response.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "eroare" field.</summary>
  public const int EroareFieldNumber = 2;
  private string eroare_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Eroare {
    get { return eroare_; }
    set {
      eroare_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "oficiuDTO" field.</summary>
  public const int OficiuDTOFieldNumber = 3;
  private global::OficiuDTO oficiuDTO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::OficiuDTO OficiuDTO {
    get { return oficiuDTO_; }
    set {
      oficiuDTO_ = value;
    }
  }

  /// <summary>Field number for the "curseDTO" field.</summary>
  public const int CurseDTOFieldNumber = 4;
  private static readonly pb::FieldCodec<global::CursaDTO> _repeated_curseDTO_codec
      = pb::FieldCodec.ForMessage(34, global::CursaDTO.Parser);
  private readonly pbc::RepeatedField<global::CursaDTO> curseDTO_ = new pbc::RepeatedField<global::CursaDTO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::CursaDTO> CurseDTO {
    get { return curseDTO_; }
  }

  /// <summary>Field number for the "participanti" field.</summary>
  public const int ParticipantiFieldNumber = 5;
  private static readonly pb::FieldCodec<global::Participant> _repeated_participanti_codec
      = pb::FieldCodec.ForMessage(42, global::Participant.Parser);
  private readonly pbc::RepeatedField<global::Participant> participanti_ = new pbc::RepeatedField<global::Participant>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Participant> Participanti {
    get { return participanti_; }
  }

  /// <summary>Field number for the "echipe" field.</summary>
  public const int EchipeFieldNumber = 6;
  private string echipe_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Echipe {
    get { return echipe_; }
    set {
      echipe_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "participantDTO" field.</summary>
  public const int ParticipantDTOFieldNumber = 7;
  private global::ParticipantDTO participantDTO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ParticipantDTO ParticipantDTO {
    get { return participantDTO_; }
    set {
      participantDTO_ = value;
    }
  }

  /// <summary>Field number for the "cursa" field.</summary>
  public const int CursaFieldNumber = 8;
  private global::Cursa cursa_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Cursa Cursa {
    get { return cursa_; }
    set {
      cursa_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Eroare != other.Eroare) return false;
    if (!object.Equals(OficiuDTO, other.OficiuDTO)) return false;
    if(!curseDTO_.Equals(other.curseDTO_)) return false;
    if(!participanti_.Equals(other.participanti_)) return false;
    if (Echipe != other.Echipe) return false;
    if (!object.Equals(ParticipantDTO, other.ParticipantDTO)) return false;
    if (!object.Equals(Cursa, other.Cursa)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::Response.Types.Type.Unknown) hash ^= Type.GetHashCode();
    if (Eroare.Length != 0) hash ^= Eroare.GetHashCode();
    if (oficiuDTO_ != null) hash ^= OficiuDTO.GetHashCode();
    hash ^= curseDTO_.GetHashCode();
    hash ^= participanti_.GetHashCode();
    if (Echipe.Length != 0) hash ^= Echipe.GetHashCode();
    if (participantDTO_ != null) hash ^= ParticipantDTO.GetHashCode();
    if (cursa_ != null) hash ^= Cursa.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Type != global::Response.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Eroare.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Eroare);
    }
    if (oficiuDTO_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(OficiuDTO);
    }
    curseDTO_.WriteTo(output, _repeated_curseDTO_codec);
    participanti_.WriteTo(output, _repeated_participanti_codec);
    if (Echipe.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Echipe);
    }
    if (participantDTO_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(ParticipantDTO);
    }
    if (cursa_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Cursa);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::Response.Types.Type.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Eroare.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Eroare);
    }
    if (oficiuDTO_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(OficiuDTO);
    }
    size += curseDTO_.CalculateSize(_repeated_curseDTO_codec);
    size += participanti_.CalculateSize(_repeated_participanti_codec);
    if (Echipe.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Echipe);
    }
    if (participantDTO_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantDTO);
    }
    if (cursa_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cursa);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::Response.Types.Type.Unknown) {
      Type = other.Type;
    }
    if (other.Eroare.Length != 0) {
      Eroare = other.Eroare;
    }
    if (other.oficiuDTO_ != null) {
      if (oficiuDTO_ == null) {
        OficiuDTO = new global::OficiuDTO();
      }
      OficiuDTO.MergeFrom(other.OficiuDTO);
    }
    curseDTO_.Add(other.curseDTO_);
    participanti_.Add(other.participanti_);
    if (other.Echipe.Length != 0) {
      Echipe = other.Echipe;
    }
    if (other.participantDTO_ != null) {
      if (participantDTO_ == null) {
        ParticipantDTO = new global::ParticipantDTO();
      }
      ParticipantDTO.MergeFrom(other.ParticipantDTO);
    }
    if (other.cursa_ != null) {
      if (cursa_ == null) {
        Cursa = new global::Cursa();
      }
      Cursa.MergeFrom(other.Cursa);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::Response.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          Eroare = input.ReadString();
          break;
        }
        case 26: {
          if (oficiuDTO_ == null) {
            OficiuDTO = new global::OficiuDTO();
          }
          input.ReadMessage(OficiuDTO);
          break;
        }
        case 34: {
          curseDTO_.AddEntriesFrom(input, _repeated_curseDTO_codec);
          break;
        }
        case 42: {
          participanti_.AddEntriesFrom(input, _repeated_participanti_codec);
          break;
        }
        case 50: {
          Echipe = input.ReadString();
          break;
        }
        case 58: {
          if (participantDTO_ == null) {
            ParticipantDTO = new global::ParticipantDTO();
          }
          input.ReadMessage(ParticipantDTO);
          break;
        }
        case 66: {
          if (cursa_ == null) {
            Cursa = new global::Cursa();
          }
          input.ReadMessage(Cursa);
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Response message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Ok")] Ok = 1,
      [pbr::OriginalName("Error")] Error = 2,
      [pbr::OriginalName("GetOficiuByUserPass")] GetOficiuByUserPass = 3,
      [pbr::OriginalName("GetAllCursa")] GetAllCursa = 4,
      [pbr::OriginalName("GetAllParticipants")] GetAllParticipants = 5,
      [pbr::OriginalName("GetEchipe")] GetEchipe = 6,
      [pbr::OriginalName("GetParticipant")] GetParticipant = 7,
      [pbr::OriginalName("GetCursa")] GetCursa = 8,
      [pbr::OriginalName("NewParticipantCursaAdded")] NewParticipantCursaAdded = 9,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
